version: "3"

services:
  react:
    build:
      context: ./react
      target: development
    container_name: react
    volumes:
      - type: bind
        source: ./react/node_modules
        target: /app/node_modules
      - type: bind
        source: ./react/.next
        target: /app/.next
      - type: bind
        source: ./react/src
        target: /app/src
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    env_file:
      - ./my_app/.my_app
