name: Latest Docker (Ubuntu) - Error

on:
  push:
    branches:
      - main
      - gh_action
      - added_difference
  workflow_dispatch:


jobs:
  run-docker-compose:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install the latest Docker
        run: |
          sudo apt-get remove -y docker docker-engine docker.io containerd runc || true
          sudo apt-get update
          sudo apt-get install -y \
            ca-certificates \
            curl \
            gnupg \
            lsb-release
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
          echo \
            "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
            $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
          docker --version

      - name: Docker Version
        run: |
          docker --version

      - name: Docker Info
        run: |
          docker info

      - name: Docker Compose Version
        run: |
          docker compose --version

      - name: containerd Version
        run: |
          containerd --version

      - name: OS Info
        run: |
          uname -a

      - name: Run Docker Compose
        run: |
          docker compose -f docker-compose.broken.yml up
