name: Docker Desktop v4.35~ (Ubuntu) - Works

on:
  push:
    branches:
      - main
      - gh_action
      - added_difference
  workflow_dispatch:

jobs:
  run-docker-compose:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install specific versions of Docker
        run: |

          # Remove any existing Docker installation
          sudo apt-get remove -y docker docker-engine docker.io containerd runc || true
          sudo apt-get update

          # Install prerequisites
          sudo apt-get install -y \
            ca-certificates \
            curl \
            gnupg \
            lsb-release

          # Add Docker's GPG key
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

          # Download specific versions of Docker packages
          wget https://download.docker.com/linux/ubuntu/dists/noble/pool/stable/amd64/containerd.io_1.7.21-1_amd64.deb
          wget https://download.docker.com/linux/ubuntu/dists/noble/pool/stable/amd64/docker-ce-cli_27.3.1-1~ubuntu.24.04~noble_amd64.deb
          wget https://download.docker.com/linux/ubuntu/dists/noble/pool/stable/amd64/docker-ce_27.3.1-1~ubuntu.24.04~noble_amd64.deb
          wget https://download.docker.com/linux/ubuntu/dists/noble/pool/stable/amd64/docker-compose-plugin_2.29.7-1~ubuntu.24.04~noble_amd64.deb

          # Install downloaded packages
          sudo dpkg -i containerd.io_1.7.21-1_amd64.deb
          sudo dpkg -i docker-ce-cli_27.3.1-1~ubuntu.24.04~noble_amd64.deb
          sudo dpkg -i docker-ce_27.3.1-1~ubuntu.24.04~noble_amd64.deb
          sudo dpkg -i docker-compose-plugin_2.29.7-1~ubuntu.24.04~noble_amd64.deb

          # Clean up downloaded .deb files
          rm containerd.io_1.7.21-1_amd64.deb \
            docker-ce-cli_27.3.1-1~ubuntu.24.04~noble_amd64.deb \
            docker-ce_27.3.1-1~ubuntu.24.04~noble_amd64.deb \
            docker-compose-plugin_2.29.7-1~ubuntu.24.04~noble_amd64.deb

          # Verify installed versions
          echo "Installed Docker Components:"
          docker --version
          docker compose --version
          containerd --version

      - name: Docker Version
        run: |
          docker --version

      - name: Docker Info
        run: |
          docker info

      - name: Docker Compose Version
        run: |
          docker compose --version

      - name: containerd Version
        run: |
          containerd --version

      - name: OS Info
        run: |
          uname -a

      - name: Run Docker Compose
        run: |
          docker compose -f docker-compose.old.works.yml up
