name: Latest Docker (Ubuntu) - Error

on:
  push:
    branches:
      - main
      - gh_action
      - added_difference
  workflow_dispatch:

jobs:
  run-docker-compose:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install specific version of Docker
        run: |
          echo "Step 1: Installing specific versions of Docker and its components..."
          sudo apt-get remove -y docker docker-engine docker.io containerd runc || true
          sudo apt-get update
          sudo apt-get install -y \
            ca-certificates \
            curl \
            gnupg \
            lsb-release

          # Add Docker's official GPG key
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

          # Set up the Docker repository
          echo \
            "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
            $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

          sudo apt-get update

          # Install specific versions
          sudo apt-get install -y \
            docker-ce=5:27.3.1~3-0~ubuntu-$(lsb_release -cs) \
            docker-ce-cli=5:27.3.1~3-0~ubuntu-$(lsb_release -cs) \
            containerd.io=1.7.2-1 \
            docker-compose-plugin=2.29.7-1

          # Verify versions
          echo "Installed Docker Versions:"
          docker --version
          docker-compose --version
          containerd --version


      - name: Docker Version
        run: |
          echo "Docker Version:"
          docker --version

      - name: Docker Info
        run: |
          echo "Docker Version:"
          docker info

      - name: OS Info
        run: |
          echo "Operating System Details:"
          uname -a

      - name: Run Docker Compose
        run: |
          docker compose -f docker-compose.broken.yml up
